name       : dia
version    : 0.97.3
release    : 4
source     :
    - http://ftp.gnome.org/pub/gnome/sources/dia/0.97/dia-0.97.3.tar.xz : 22914e48ef48f894bb5143c5efc3d01ab96e0a0cde80de11058d3b4301377d34
license    : GPL-2.0
component  : office
summary    : Dia Diagram Editor
description: Dia Diagram Editor is free Open Source drawing software. Dia supports more than 30 different diagram types like flowcharts, network diagrams, database models. More than a thousand readymade
    objects help to draw professional diagrams. Dia can read and write a number of different raster and vector image formats.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(ice)
    - pkgconfig(libart-2.0)
    - pkgconfig(libgnomeui-2.0)
    - pkgconfig(pango)
    - pkgconfig(sm)
patterns   :
    - /usr/share/man
setup      : |
    %configure --disable-static \
        --enable-gnome \
        --with-python
build      : |
    %make
install    : |
    %make_install
    sed -i 's/%F/--integrated %F/' $installdir/usr/share/applications/dia.desktop
