name       : dia
version    : 0.97.2
release    : 2
source     :
    - http://skylink.dl.sourceforge.net/project/dia-installer/dia/0.97.2/dia-0.97.2.tar.xz : a761478fb98697f71b00d3041d7c267f3db4b94fe33ac07c689cb89c4fe5eae1
license    : GPL-2.0
summary    : Dia Diagram Editor
description: |
    Dia Diagram Editor is free Open Source drawing software for Windows, Mac OS X and Linux. Dia supports more than 30 different diagram types like flowcharts, network diagrams, database models. More than a thousand readymade objects help to draw professional diagrams. Dia can read and write a number of different raster and vector image formats. Software developers and database specialists can use Dia as a CASE tool to generate code skeletons from their drawings. Dia can be scripted and extended using Python. 
builddeps  :
    - pkgconfig(QtCore)
    - pkgconfig(pango)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-2.0)
patterns   :
    - /usr/share/man
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
