name       : dia
version    : 0.97.3
release    : 9
source     :
    - https://download.gnome.org/sources/dia/0.97/dia-0.97.3.tar.xz : 22914e48ef48f894bb5143c5efc3d01ab96e0a0cde80de11058d3b4301377d34
license    : GPL-2.0-only
component  : office
summary    : Dia Diagram Editor
description: |
    Dia Diagram Editor is free Open Source drawing software. Dia supports more than 30 different diagram types like flowcharts, network diagrams, database models. More than a thousand readymade objects help to draw professional diagrams. Dia can read and write a number of different raster and vector image formats.
builddeps  :
    - pkgconfig(libgnomeui-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(popt)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(sm)
    - docbook-xml
    - swig
patterns   :
    - /usr/share/man
setup      : |
    %patch -p1 < $pkgfiles/0001-Set-anti-aliasing-to-be-the-default.patch
    %configure --disable-static --enable-gnome --with-swig --with-python
build      : |
    %make
install    : |
    %make_install
